app.imageDirectory: D:\Storage\Images\
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/catsgram
    username: postgres
    password: Password
    driver-class-name: org.postgresql.Driver
logging.level:
  ru.yandex.practicum.catsgram: DEBUG
  org.zalando.logbook: TRACE