app.imageDirectory: /home/alex/images
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userdb
    username: dbuser
    password: password
    driver-class-name: org.postgresql.Driver
logging.level:
  ru.yandex.practicum.catsgram: DEBUG
  org.zalando.logbook: TRACE